version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: bookit
      MYSQL_USER: bookit
      MYSQL_PASSWORD: hej
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
   devDB:
