version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookit
      MYSQL_USER: bookit
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - OAUTH_ID=xxx
      - OAUTH_SECRET=xxx
    depends_on:
      - db
volumes:
   devDB:
