version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookit
      MYSQL_USER: bookit
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c 'rm -f tmp/pids/server.pid && sleep 10 && sh start.sh'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      OAUTH_ID: id
      OAUTH_SECRET: secret
      ACCOUNT_ADDRESS: http://gamma-backend:8081
      ACCOUNT_ADDRESS_REDIRECT: http://localhost:8081
      DATABASE_HOST: db
    ports:
      - 3001:3001
  gamma-backend:
    image: cthit/gamma-backend
    environment:
      DB_HOST: gamma_db
      SERVER_PORT: 8081
      SUCCESSFUL_LOGIN: http://localhost:3000
      DEFAULT_CLIENT_NAME: name
      DEFAULT_CLIENT_ID: id
      DEFAULT_CLIENT_SECRET: secret
      DEFAULT_REDIRECT_URI: http://localhost:3001/auth/account/callback
      DEFAULT_API_KEY: key
      ROOT_DEBUG_LEVEL: INFO
      IS_MOCKING_CLIENT: "true"
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      COOKIE_DOMAIN: localhost
    ports:
      - 8081:8081
    depends_on:
      - gamma_db
  gamma_frontend:
    image: cthit/gamma-frontend:development
    environment:
      HTTP_PROXY: http://gamma-backend:8081
      REACT_APP_BACKEND_URL: http://localhost:8081/api
      REACT_APP_FRONTEND_URL: http://localhost:3000
    ports:
      - 3000:3000
  gamma_db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    restart: always
    ports:
    - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8082:8080
  redis:
    image: redis
    ports:
    - 6379:6379
volumes:
  devDB:
