version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookit
      MYSQL_USER: bookit
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c 'rm -f tmp/pids/server.pid && sh start.sh'
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
volumes:
   devDB:
