version: '2'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookit
      MYSQL_USER: bookit
      MYSQL_PASSWORD: iamapassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c "sh wait_for_db.sh && sh start.sh"  
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
