version: '3'
services:
    db:
        image: nouchka/sqlite3
        volumes:
            - devdb:/opt/sqlite/
    web:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
volumes:
    devdb:

